# Limits
LIMITE_DIA = 65
LIMITE_NOCHE = 55
LIMITE_TARDE = 55

# Periods
PERIODO_AGREGACION = 900  # Seconds

# Plotting Flags
PLOT_TIME = True
PLOT_HEATMAP = False
PLOT_INDHEATMAP = False
PLOT_DAY_EVOLUTION = False
PLOT_PERIOD_EVOLUTION = False
PLOT_NIGHT_EVOLUTION = False
