# Limits
LIMITE_DIA = 65
LIMITE_NOCHE = 55
LIMITE_TARDE = 55

# Periods
PERIODO_AGREGACION = 900  # Seconds

# Plotting Flags
PLOT_TIME = True
PLOT_HEATMAP = True
PLOT_INDHEATMAP = True
PLOT_DAY_EVOLUTION = False
PLOT_PERIOD_EVOLUTION = True
PLOT_NIGHT_EVOLUTION = True

# PERCENTILES Settings
PERCENTILES = PERIODO_AGREGACION > 299
