"""add alarm aggregation seconds

Revision ID: 0dea1449cb1d
Revises: f29439d75b4e
Create Date: 2026-10-06 10:43:16.287585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0dea1449cb1d'
down_revision: Union[str, Sequence[str], None] = 'f29439d75b4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "alarma_acustica",
        sa.Column("aggregation_seconds", sa.Float(), nullable=True),
    )

    op.execute(
        "UPDATE alarma_acustica "
        "SET aggregation_seconds = 3600 "
        "WHERE aggregation_seconds IS NULL"
    )

    op.alter_column(
        "alarma_acustica",
        "aggregation_seconds",
        existing_type=sa.Float(),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alarma_acustica', 'aggregation_seconds')
    # ### end Alembic commands ###
