"""add peak sample count

Revision ID: 1147c719252e
Revises: e88cd704a2a8
Create Date: 2026-10-02 12:01:49.881054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1147c719252e'
down_revision: Union[str, Sequence[str], None] = 'e88cd704a2a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pico_acustico', sa.Column('sample_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pico_acustico', 'sample_count')
    # ### end Alembic commands ###
