"""create core noiseport schema

Revision ID: 14f9046680c3
Revises: 
Create Date: 2026-09-28 09:57:49.359635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14f9046680c3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campania',
    sa.Column('id_campania', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('referencia_interna', sa.String(length=255), nullable=False),
    sa.Column('fecha_inicio', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_fin', sa.DateTime(timezone=True), nullable=True),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id_campania')
    )
    op.create_table('dispositivo',
    sa.Column('id_dispositivo', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=256), nullable=False),
    sa.Column('requiere_calibracion', sa.Boolean(), nullable=False),
    sa.Column('valor_calibracion', sa.Float(), nullable=True),
    sa.Column('fecha_calibracion', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id_dispositivo')
    )
    op.create_table('punto',
    sa.Column('id_punto', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('municipio', sa.String(length=255), nullable=False),
    sa.Column('latitud', sa.Float(), nullable=True),
    sa.Column('longitud', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id_punto')
    )
    op.create_table('contexto',
    sa.Column('id_contexto', sa.Integer(), nullable=False),
    sa.Column('id_punto', sa.Integer(), nullable=False),
    sa.Column('id_dispositivo', sa.Integer(), nullable=False),
    sa.Column('id_campania', sa.Integer(), nullable=False),
    sa.Column('altura', sa.Float(), nullable=True),
    sa.Column('soporte', sa.String(length=255), nullable=True),
    sa.Column('fecha_inicio', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_fin', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['id_campania'], ['campania.id_campania'], ),
    sa.ForeignKeyConstraint(['id_dispositivo'], ['dispositivo.id_dispositivo'], ),
    sa.ForeignKeyConstraint(['id_punto'], ['punto.id_punto'], ),
    sa.PrimaryKeyConstraint('id_contexto')
    )
    op.create_index('ix_contexto_punto_campania_dispositivo', 'contexto', ['id_punto', 'id_campania', 'id_dispositivo'], unique=False)
    op.create_table('archivo',
    sa.Column('id_archivo', sa.Integer(), nullable=False),
    sa.Column('id_contexto', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=1024), nullable=False),
    sa.Column('hash', sa.String(length=1024), nullable=True),
    sa.Column('duracion_seconds', sa.Float(), nullable=True),
    sa.Column('datetime_inicio', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sample_rate_hz', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_contexto'], ['contexto.id_contexto'], ),
    sa.PrimaryKeyConstraint('id_archivo')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('archivo')
    op.drop_index('ix_contexto_punto_campania_dispositivo', table_name='contexto')
    op.drop_table('contexto')
    op.drop_table('punto')
    op.drop_table('dispositivo')
    op.drop_table('campania')
    # ### end Alembic commands ###
