"""add device type

Revision ID: 269b8014cee1
Revises: 6d2064cf7e5c
Create Date: 2026-09-29 08:57:29.572737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '269b8014cee1'
down_revision: Union[str, Sequence[str], None] = '6d2064cf7e5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dispositivo', sa.Column('tipo', sa.String(length=64),server_default="unknown", nullable=False))
    op.create_index(op.f('ix_dispositivo_tipo'), 'dispositivo', ['tipo'], unique=False)
    op.alter_column("dispositivo","tipo",server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dispositivo_tipo'), table_name='dispositivo')
    op.drop_column('dispositivo', 'tipo')
    # ### end Alembic commands ###
