"""unique source file per context

Revision ID: 6d2064cf7e5c
Revises: 7946f55d67b7
Create Date: 2026-09-28 16:17:36.378116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d2064cf7e5c'
down_revision: Union[str, Sequence[str], None] = '7946f55d67b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_archivo_contexto_filename', 'archivo', ['id_contexto', 'filename'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_archivo_contexto_filename', 'archivo', type_='unique')
    # ### end Alembic commands ###
