"""add per-file processing stages

Revision ID: 73ad710c586b
Revises: 0dea1449cb1d
Create Date: 2026-10-07 12:55:45.451896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73ad710c586b'
down_revision: Union[str, Sequence[str], None] = '0dea1449cb1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('archivo_procesamiento',
    sa.Column('id_archivo', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(length=64), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_archivo'], ['archivo.id_archivo'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_archivo', 'stage')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('archivo_procesamiento')
    # ### end Alembic commands ###
