"""allow acoustic measurement without source file

Revision ID: 7946f55d67b7
Revises: 6913242aeb68
Create Date: 2026-09-28 12:43:55.228371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7946f55d67b7'
down_revision: Union[str, Sequence[str], None] = '6913242aeb68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('medicion_acustica', 'id_archivo',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('medicion_acustica', 'id_archivo',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
