"""stabilize acoustic measurement identity

Revision ID: 8305f0061287
Revises: c73019640cb6
Create Date: 2026-09-30 11:09:05.183046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8305f0061287'
down_revision: Union[str, Sequence[str], None] = 'c73019640cb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_medicion_archivo_datetime_aggregation', 'medicion_acustica', ['id_archivo', 'datetime', 'aggregation_seconds'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_medicion_archivo_datetime_aggregation', 'medicion_acustica', type_='unique')
    # ### end Alembic commands ###
