"""add processing software version

Revision ID: b3c8bf3b4f85
Revises: 73ad710c586b
Create Date: 2026-10-08 09:44:56.007982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3c8bf3b4f85'
down_revision: Union[str, Sequence[str], None] = '73ad710c586b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('archivo_procesamiento', sa.Column('software_version', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('archivo_procesamiento', 'software_version')
    # ### end Alembic commands ###
