"""add acoustic third octave measurements

Revision ID: c73019640cb6
Revises: 269b8014cee1
Create Date: 2026-09-29 14:38:12.122332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c73019640cb6'
down_revision: Union[str, Sequence[str], None] = '269b8014cee1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medicion_acustica_en_tercios',
    sa.Column('id_medicion', sa.Integer(), nullable=False),
    sa.Column('band_12_5_db', sa.Float(), nullable=True),
    sa.Column('band_16_db', sa.Float(), nullable=True),
    sa.Column('band_20_db', sa.Float(), nullable=True),
    sa.Column('band_25_db', sa.Float(), nullable=True),
    sa.Column('band_31_5_db', sa.Float(), nullable=True),
    sa.Column('band_40_db', sa.Float(), nullable=True),
    sa.Column('band_50_db', sa.Float(), nullable=True),
    sa.Column('band_63_db', sa.Float(), nullable=True),
    sa.Column('band_80_db', sa.Float(), nullable=True),
    sa.Column('band_100_db', sa.Float(), nullable=True),
    sa.Column('band_125_db', sa.Float(), nullable=True),
    sa.Column('band_160_db', sa.Float(), nullable=True),
    sa.Column('band_200_db', sa.Float(), nullable=True),
    sa.Column('band_250_db', sa.Float(), nullable=True),
    sa.Column('band_315_db', sa.Float(), nullable=True),
    sa.Column('band_400_db', sa.Float(), nullable=True),
    sa.Column('band_500_db', sa.Float(), nullable=True),
    sa.Column('band_630_db', sa.Float(), nullable=True),
    sa.Column('band_800_db', sa.Float(), nullable=True),
    sa.Column('band_1000_db', sa.Float(), nullable=True),
    sa.Column('band_1250_db', sa.Float(), nullable=True),
    sa.Column('band_1600_db', sa.Float(), nullable=True),
    sa.Column('band_2000_db', sa.Float(), nullable=True),
    sa.Column('band_2500_db', sa.Float(), nullable=True),
    sa.Column('band_3150_db', sa.Float(), nullable=True),
    sa.Column('band_4000_db', sa.Float(), nullable=True),
    sa.Column('band_5000_db', sa.Float(), nullable=True),
    sa.Column('band_6300_db', sa.Float(), nullable=True),
    sa.Column('band_8000_db', sa.Float(), nullable=True),
    sa.Column('band_10000_db', sa.Float(), nullable=True),
    sa.Column('band_12500_db', sa.Float(), nullable=True),
    sa.Column('band_16000_db', sa.Float(), nullable=True),
    sa.Column('band_20000_db', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['id_medicion'], ['medicion_acustica.id_medicion'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_medicion')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('medicion_acustica_en_tercios')
    # ### end Alembic commands ###
