"""add acoustic measurement table

Revision ID: e88899bf6c79
Revises: 14f9046680c3
Create Date: 2026-09-28 11:31:30.264136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e88899bf6c79'
down_revision: Union[str, Sequence[str], None] = '14f9046680c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medicion_acustica',
    sa.Column('id_medicion', sa.Integer(), nullable=False),
    sa.Column('id_contexto', sa.Integer(), nullable=False),
    sa.Column('id_archivo', sa.Integer(), nullable=False),
    sa.Column('datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('aggregation_seconds', sa.Float(), nullable=False),
    sa.Column('la_db', sa.Float(), nullable=True),
    sa.Column('lc_db', sa.Float(), nullable=True),
    sa.Column('lz_db', sa.Float(), nullable=True),
    sa.Column('la_max_db', sa.Float(), nullable=True),
    sa.Column('la_min_db', sa.Float(), nullable=True),
    sa.Column('lc_la_db', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['id_archivo'], ['archivo.id_archivo'], ),
    sa.ForeignKeyConstraint(['id_contexto'], ['contexto.id_contexto'], ),
    sa.PrimaryKeyConstraint('id_medicion')
    )
    op.create_index(op.f('ix_medicion_acustica_datetime'), 'medicion_acustica', ['datetime'], unique=False)
    op.create_index(op.f('ix_medicion_acustica_id_archivo'), 'medicion_acustica', ['id_archivo'], unique=False)
    op.create_index(op.f('ix_medicion_acustica_id_contexto'), 'medicion_acustica', ['id_contexto'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_medicion_acustica_id_contexto'), table_name='medicion_acustica')
    op.drop_index(op.f('ix_medicion_acustica_id_archivo'), table_name='medicion_acustica')
    op.drop_index(op.f('ix_medicion_acustica_datetime'), table_name='medicion_acustica')
    op.drop_table('medicion_acustica')
    # ### end Alembic commands ###
