"""add acoustic peaks

Revision ID: e88cd704a2a8
Revises: b483c0270137
Create Date: 2026-10-02 11:57:58.584344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e88cd704a2a8'
down_revision: Union[str, Sequence[str], None] = 'b483c0270137'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pico_acustico',
    sa.Column('id_pico', sa.Integer(), nullable=False),
    sa.Column('id_contexto', sa.Integer(), nullable=False),
    sa.Column('id_archivo_pico', sa.Integer(), nullable=True),
    sa.Column('id_medicion_pico', sa.Integer(), nullable=False),
    sa.Column('datetime_pico', sa.DateTime(timezone=True), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=False),
    sa.Column('peak_la_db', sa.Float(), nullable=False),
    sa.Column('leq_db', sa.Float(), nullable=False),
    sa.Column('prominence_db', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['id_archivo_pico'], ['archivo.id_archivo'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id_contexto'], ['contexto.id_contexto'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_medicion_pico'], ['medicion_acustica.id_medicion'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_pico'),
    sa.UniqueConstraint('id_medicion_pico', name='uq_pico_medicion_pico')
    )
    op.create_index(op.f('ix_pico_acustico_datetime_pico'), 'pico_acustico', ['datetime_pico'], unique=False)
    op.create_index(op.f('ix_pico_acustico_id_archivo_pico'), 'pico_acustico', ['id_archivo_pico'], unique=False)
    op.create_index(op.f('ix_pico_acustico_id_medicion_pico'), 'pico_acustico', ['id_medicion_pico'], unique=False)
    op.create_table('pico_acustico_medicion',
    sa.Column('id_pico', sa.Integer(), nullable=False),
    sa.Column('id_medicion', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_medicion'], ['medicion_acustica.id_medicion'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_pico'], ['pico_acustico.id_pico'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_pico', 'id_medicion')
    )
    op.create_index(op.f('ix_pico_acustico_medicion_id_medicion'), 'pico_acustico_medicion', ['id_medicion'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pico_acustico_medicion_id_medicion'), table_name='pico_acustico_medicion')
    op.drop_table('pico_acustico_medicion')
    op.drop_index(op.f('ix_pico_acustico_id_medicion_pico'), table_name='pico_acustico')
    op.drop_index(op.f('ix_pico_acustico_id_archivo_pico'), table_name='pico_acustico')
    op.drop_index(op.f('ix_pico_acustico_datetime_pico'), table_name='pico_acustico')
    op.drop_table('pico_acustico')
    # ### end Alembic commands ###
