"""add acoustic alarms

Revision ID: f29439d75b4e
Revises: 1147c719252e
Create Date: 2026-10-05 16:11:41.517273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f29439d75b4e'
down_revision: Union[str, Sequence[str], None] = '1147c719252e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alarma_acustica',
    sa.Column('id_alarma', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_contexto', sa.Integer(), nullable=False),
    sa.Column('alarm_type', sa.String(length=50), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('threshold', sa.Float(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['id_contexto'], ['contexto.id_contexto'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_alarma'),
    sa.UniqueConstraint('id_contexto', 'alarm_type', 'start_time', 'end_time', name='uq_alarma_contexto_tipo_intervalo')
    )
    op.create_index(op.f('ix_alarma_acustica_id_contexto'), 'alarma_acustica', ['id_contexto'], unique=False)
    op.create_table('alarma_acustica_medicion',
    sa.Column('id_alarma', sa.Integer(), nullable=False),
    sa.Column('id_medicion', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_alarma'], ['alarma_acustica.id_alarma'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_medicion'], ['medicion_acustica.id_medicion'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_alarma', 'id_medicion')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alarma_acustica_medicion')
    op.drop_index(op.f('ix_alarma_acustica_id_contexto'), table_name='alarma_acustica')
    op.drop_table('alarma_acustica')
    # ### end Alembic commands ###
