campaign:
  name:               "CAMPAÑA TEST ACLIMA"
  input_root:         "/home/martin/Campañas de test/ACLIMA/C1/3-Medidas"
  output_root:        "/home/martin/Campañas de test/ACLIMA/C1/5-Resultados"
  timezone:           "Europe/Madrid"

execution:
  profile:              manual
  stop_on_error:        false

profiles:

  manual:

    run_spl: true
    run_ai: true
    run_peaks: false
    run_alarms: false
    run_basic_visualization: true
    run_advanced_visualization: false

  hourly:

    run_spl: true
    run_ai: true
    run_peaks: true
    run_alarms: true
    run_basic_visualization: false
    run_advanced_visualization: true

discovery:
  filter_campaign:      null
  filter_point:         'P3 - test'
  filter_device:        'audiomoth'

devices:
  audiomoth:
    folder_name:       "AUDIOMOTH"
    default_needs_spl:  true
    default_needs_ai:   true
    default_visualize:  true

  sonometer:
    folder_name:       "SONOMETRO"
    default_needs_spl:  false
    default_needs_ai:   false
    default_visualize:  true

  sv307:
    folder_name:       'SV307'
    default_needs_spl:  false
    default_needs_ai:   false
    default_visualize:  true

spl:
  enabled:              true
  calibration_file:     "devices.yaml"
  filter_campaign:      null
  filter_point:         null
  output_subfolder:     "SPL"
  third_octave:
    enabled: true
    fraction: 3
    fmin: 20
    fmax: 20000

ai:
  enabled:              true
  model:                "urban"
  top_k:                3
  window_seconds:       5
  threshold:            0.30
  save_embeddings:      false
  save_spectrograms:    false
  filter_point: null

peaks:

  enabled:              true
  window_size:          30
  adding_threshold:     5
  width:                2
  prominence:           3

alarms:

  enabled:              true
  mode:                 urban
  oca_limit:            OCA_RESIDENTIAL
  aggregation_seconds:  3600
  probability_threshold: 0.30

  lmax:
    threshold_db:           95

  lc_la:
    normative_threshold_db: 10
    dynamic_threshsold_db:  3

  l90:
    threshold_db:           5
    rolling_window:         3

  frequency_composition:
    jump_threshold_db:      5

  tonal:
    enabled:                true
  
visualization:
  enabled:              true
  taxonomy:             "urban"
  aggregation_seconds:  900
  percentiles:          [90, 10]
  oca_type:             "OCA_RESIDENTIAL"
  remove_start_seconds: 900
  remove_end_seconds:   900
  tenerife_timezone:    true

outputs:
  create_point_folder:  true
  subfolders:

    general:
      medidas_folder_name:           "3-Medidas"
      resultados_folder_name:        "5-Resultados"  
    ai:                   
      general_folder_name:           "AI_MODEL"
      visualization_folder_name:     "Visualizations"
      predictions_folder_name:       "Predictions"
    spl:        
      general_folder_name:           "SPL"
      visualization_folder_name:     "Visualizations"  
      values_folder_name:           "Values"

    logs:                 "logs"

database:
  enabled:                true
  url_env:                "DATABASE_URL"
  echo:                   false

points:
  example:
    correction_db:      0.0
    new_date:           null
    new_time:           null
    threshold_date:     null
    threshold_time:     null

  ZARAUTZ_C1_P1:
    correction_db:      -1.2
    new_date:           null
    new_time:           null
    threshold_date:     null
    threshold_time:     null